// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsfmzuldhrdvmwfiwlre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZm16dWxkaHJkdm13Zml3bHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1ODYwNzcsImV4cCI6MjA2MTE2MjA3N30.HZv-JwEQXiMTecXnoPivFuZ0NQ-A9GB7YJew6FfXR3o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);